---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/apren173/variedadescr.com/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R .env.production $DEPLOYPATH/.env
    - /bin/cp -R composer.lock $DEPLOYPATH/
    - /bin/cp -R composer.json $DEPLOYPATH/

    - cd $DEPLOYPATH
    #- /bin/chmod 755 storage bootstrap/cache
    - /usr/local/bin/composer install --no-dev
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache 
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
    - /bin/cp -R public/build $DEPLOYPATH/public/