---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/apren173/variedadescr.com/
    - echo "Starting deployment at $(date)" >> deployment.log
    - /bin/cp -R app bootstrap config database public resources routes views $DEPLOYPATH
 