---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/apren173/variedadescr.com/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/php /usr/local/bin/composer install --no-dev
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/bin/npm install
    - /usr/bin/npm run build