---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/apren173/variedadescr.com/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - echo "Starting deployment process" >> deployment.log
    - /usr/local/bin/php /usr/local/bin/composer install --no-dev >> deployment.log 2>&1
    - /usr/local/bin/php artisan config:cache >> deployment.log 2>&1
    - /usr/bin/npm install >> deployment.log 2>&1
    - /usr/bin/npm run build >> deployment.log 2>&1